#!/bin/sh
PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

SEDUTIL="sedutil-cli.badicsalex"

list_block_devices()
{
	wait_for_udev 10
	/usr/bin/find /dev/ -name 'sd[a-z]' -or -name 'nvme[0-9]n[0-9]' -or -name 'nvme[0-9][0-9]n[0-9][0-9]'
	if [ $? != 0 ] ; then
		panic "Unable to list block devices"
	fi
}

is_opal_drive()
{
	"$SEDUTIL" --query "$1" > /dev/null 2> /dev/null
	return $?
}

is_opal_locked()
{
	"$SEDUTIL" --query "$1" 2> /dev/null | grep -q "Locked = Y"
	return $?
}

get_block_device_info()
{
	"$SEDUTIL" --query "$1" | gawk '/^\//{print;exit}'
	if [ $? != 0 ] ; then
		panic "Unable to query $1"
	fi
}

opal_unlock()
{
	while true ; do
		/usr/bin/stty -echo
		echo -n "Password for $1 ($2): "
		read pass
		/usr/bin/stty echo
		"$SEDUTIL" --setlockingrange 1 rw "$pass" "$1"
		if [ $? != 0 ] ; then
			log_failure_msg "Failed to unlock $1 ($2)!"
			continue
		fi
		"$SEDUTIL" --prepareForS3Sleep 1 "$pass" "$1"
		if [ $? != 0 ] ; then
			panic "prepare for S3 failed for $1"
		fi
		log_success_msg "Unlocked $1 ($2)!"
		break
	done
}

log_begin_msg "OPAL Drives Unlock"
for block_device in $(list_block_devices) ; do
	if ! is_opal_drive "$block_device" ; then
		continue
	fi
	if ! is_opal_locked "$block_device" ; then
		continue
	fi
	opal_unlock "$block_device" "$(get_block_device_info $block_device)"
done
log_end_msg

/usr/sbin/partprobe