#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/sedutil-cli.badicsalex
copy_exec /usr/bin/clear
copy_exec /usr/bin/find
copy_exec /usr/bin/gawk
copy_exec /usr/bin/gawk
copy_exec /usr/bin/grep
copy_exec /usr/bin/readlink
copy_exec /usr/bin/stty
copy_exec /usr/bin/xargs
copy_exec /usr/sbin/partprobe